# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito')], max_length=2)),
                ('ruc_emisor', models.CharField(max_length=11)),
                ('serie', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=8)),
                ('ruc_cliente', models.CharField(blank=True, max_length=11, null=True)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('direccion_cliente', models.TextField(blank=True, null=True)),
                ('total_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_igv', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='xml/')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='zip/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('GENERADO', 'Generado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('errores', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comprobante Electrónico',
                'verbose_name_plural': 'Comprobantes Electrónicos',
                'db_table': 'comprobantes',
            },
        ),
        migrations.CreateModel(
            name='DetalleComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comprobantes.comprobante')),
            ],
            options={
                'verbose_name': 'Detalle de Comprobante',
                'verbose_name_plural': 'Detalles de Comprobante',
                'db_table': 'detalles_comprobante',
            },
        ),
        migrations.AlterUniqueTogether(
            name='comprobante',
            unique_together={('tipo_comprobante', 'ruc_emisor', 'serie', 'numero')},
        ),
    ] 